service:
  port: 8080
  host: "0.0.0.0"
  root_path: ""
  name: "tm-service"
app:
  logging_conf_path: "./resources/logging.ini"
  use_scheduler: true
  use_rest_api: true
  use_ke_api: true
#db does not require env prefix
#TODO: make db as prefix -> db_host = "DB_" + "HOST"
db:
  db_host: "postgres"
  db_user: "postgres"
  db_name: "postgres"
  db_port: 5432
  #  db_pass:
  db_log_query: false
  db_log_error_query: true
  db_max_rows: 100000
  #  db_init_script_location: "path/to/script.sql"
  db_table_prefix: "tm_"
  db_schema_name: "public"
  db_init: false
ke:
  ki_config_path: "/app/resources/ke_config.yaml"
  ki_vars:
    DAY_DURATION: '"PT1440M"^^xsd:duration'
    ISP_UNIT: '"PT15M"^^xsd:duration'