entsoe_api:
  subscribed_eic:
    - code: 10YPL-AREA-----S
      market_types:
        - "day_ahead"
    - code: 10Y1001A1001A82H
      market_types:
        - "day_ahead"
    - code: 10YAT-APG------L
      market_types:
        - "day_ahead"
    - code: 10YBE----------2
      market_types:
        - "day_ahead"
    - code: 10YES-REE------0
      market_types:
        - "intraday"
        - "day_ahead"
  #       - intraday
  eic_codes:
    10Y1001A1001A82H:
      code: "10Y1001A1001A82H"
      area_names:
        - "BZN|DE-LU"
      country_codes:
        - "Germany"
        - "DE"
    10YPL-AREA-----S:
      code: "10YPL-AREA-----S"
      area_names:
        - "BZN|PL"
      country_codes:
        - "Poland"
        - "PL"
    10YAT-APG------L:
      code: "10YAT-APG------L"
      area_names:
        - "BZN|AT"
      country_codes:
        - "Austria"
        - "AT"
    10YES-REE------0:
      code: "10YES-REE------0"
      area_names:
        - "BZN|ES"
      country_codes:
        - "Spain"
        - "ES"
    10YBE----------2:
      code: "10YBE----------2"
      area_names:
        - "BZN|BE"
      country_codes:
        - "Belgium"
        - "BE"
